name: SSH to EC2
on:
  push:
    branches:
      - main
jobs:
  ssh-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2 and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            source ~/.nvm/nvm.sh &&
            nvm use 21.7.3 &&
            cd demo-next
            git pull origin main
            npm run build
            pm2 restart nextjs-server
